spring:
  application:
    name: guitarapp

  datasource:
    url: jdbc:postgresql://localhost:5432/guitar_db
    username: postgres
    password: secret

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

security:
  user:
    name: admin
    password: secret123

jwt:
  secret: thisIsMysecregtfrdesww233eggtffeeddgkjjhhtdhttebd54ndhdhfhhhshs8877465sbbdd
  expiration: 3600000